LucianoCirino/efficiency-nodes-comfyui

efficiency_nodes.py

I've learned my lesson and turned off the formatter.

Small cleanups

---

efficiency_nodes.py

This can be done super simple with the hidden variable "MY_UNIQUE_ID"

Fix KSampler Unique ID Code

---

efficiency_nodes.py

***Efficiency Nodes v1.57 Updates***
- 4 new XY Plot Input nodes HAVE BEEN ADDED: "Positive Prompt S/R", "Negative Prompt S/R",
"Clip Skip", and "Manual XY Entry". 
- Renamed the 'Join XY Inputs' node to 'Join XY Inputs of Same Type' to aliviate confusion.
- Efficient Loader LoRAs now get applied also to "Checkpoint" XY Plots.
- 'cache_settings.json' has been renamed 'node_settings.json'.
- Added a few new customizable node options on the 'node_settings.json'.
- Fixed a bug where the Efficient Loader would not clear its models cache properly, causing
it to repeatedly load models (ckpt/vae/lora) after any changes.
- Cleaned and fixed XY Plot console printouts.
- Fixed text clipping issues with the XY Plot's Y_labels.
- Fixed a bug where the XY Plot Image results did not always visibly …

v1.57 Efficiency Nodes

---

efficiency_nodes.py

Gives user the ability to output the preview image through the IMAGE output only.

Added 'Output Only' option to KSampler

---

efficiency_nodes.py
node_settings.json

Moved the xy_plot_as_output_image setting from the json into the XY Plot node.

KSampler XY Plot Output Behavior Option

---

efficiency_nodes.py

Fixed issue where conditioning was not properly encoded by Efficient Loader and XY-Plots.

Efficient Loader SDXL Patch

---

efficiency_nodes.py

simpleeval-fix-2

---

tsc_utils.py

Auto required package isntaller package now uses the "requirements.txt" folder as reference for what packages to install.  Packages are also now installed straight to the ComfyUI's python embedded site-packages folder via relative pathing.  Updated messages to be cleaner on console aswell.

Auto Package Installer Changes

---

tsc_utils.py

Set WebSocket server thread to daemon to ensure it exits with main program.

Set async thread to daemon

---

tsc_utils.py

- Introduced `handle_websocket_failure()` to consolidate error handling and messaging.
- Removed redundant `websocket_status` checks in the server initialization function.
- Enhanced the `send_command_to_frontend()` function to handle potential WebSocket failures.
- Ensured error messages related to WebSocket failures are displayed only once.

Improve WebSocket error handling and connectivity

---

tsc_utils.py

Refined the server_logic function to better manage WebSocket disruptions:
- Integrated `handle_websocket_failure()` directly into `server_logic` to capture and inform about unexpected disconnection scenarios.
- Added conditionals to reset the `latest_image` when the WebSocket connection is deemed inactive.
- Ensured that the error handling mechanism is more resilient to abrupt connection terminations, especially in the context of receiving messages.

Improved server_logic WebSocket Handling

---

efficiency_nodes.py
node_settings.json
tsc_utils.py

This commit includes many changes:
- Improved installation of required python packages and improved logic when installation fails
- Moved VAE tile option from node_settings.json to the Efficient KSampler's "vae_decode" input
- Changed preview image logic, now its much less buggy

Bug Fixes + Tiled VAE moved to KSamplers

---

tsc_utils.py

LoRA loading loads through Comfy's database, ensuring future proof compatability.

Transformer/Diffuser LoRA Compatability

---

efficiency_nodes.py

Fix issues with the HiRes Script node and the KSampler's VAEtiled

HiResFix and VAEtiled Patch

---

efficiency_nodes.py

LoRA Stacker Adv Mode Patch

---

efficiency_nodes.py

1) Reintroduced Manual XY Entry Node
2) Fixed issue with KSampler outputs when in script mode
3) Unpack SDXL Tuple node was fixed
4) Plot no longer bugs out if no ckpt_name is found
5) Changed text on LoRA parameter plot printouts
6) Fixed LoRA parameters not showing on console log

Small Fixes & Updates

---

efficiency_nodes.py

1) Fixed issue where Control Net Stacks would not get applied 2) Fixed issue where XY Input Control Net was not coded whatsoever.

ControlNet Fixes (XY Input+StackApplications)

---

__init__.py
tsc_utils.py

This change comes from changes made to ComfyUI from commmit https://github.com/comfyanonymous/ComfyUI/pull/1273

Change how Web Extensions are Loaded

---

efficiency_nodes.py

Efficient Loader "Clip" output was not getting its "Clip Set Last Layer" settings applied. XY Plot was also not properly applying Clip Skips.

Fixed ClipSkip Issues (Loader & XY Plot)

---

tsc_utils.py

- Added a timeout of 7 seconds to the package installation process using subprocess.check_call. If any package installation exceeds this duration, it's terminated, and a timeout message is displayed.
- Improved error handling during package installation. If a package fails to install, the specific reason is now displayed to the user. Split the error message into two lines for better readability: one line indicates the failure, and the next line provides the specific error message.
- Instead of relying solely on pip freeze to determine installed packages, added a function to check if a package is installed by attempting to import it. This provides a more direct and reliable way to verify if a package is available for use.
- Removed the use of subprocess.getoutput which was causing hangs …

Improve Auto Package Installation

---

efficiency_nodes.py

Fixed issue where LoRA Stacks where not properly being swapped between generations

XY Input LoRA Stacks Fix

---

tsc_utils.py

Auto package installation was a huge headache and never fully worked.

Remove auto dependency installations
